APP_NAME      := femtoMerge

SOURCE_FILES  := femtoMerge.cxx
USES_RFIO     := no
USES_ORACLE   := no
USES_GFORTRAN := no

include $(HADDIR)/hades.def.mk

.PHONY:  default
default: clean build install

include $(HADDIR)/hades.app.mk