// A million includes for looping DSTs that should get out of the way
#ifndef __INCLUDES_H__
#define __INCLUDES_H__

#include "TObject.h"
#include "TROOT.h"
#include "TFile.h"
#include "TDirectory.h"
#include "TSystemDirectory.h"
#include "TSystemFile.h"
#include "TStyle.h"

#include "TString.h"
#include "TMath.h"
#include "TLorentzVector.h"
#include "TVectorD.h"
#include "TMVA/Reader.h"

#include "TList.h"
#include "TTree.h"
#include "TH1.h"
#include "TH2.h"
#include "TH3.h"
#include "THn.h"
#include "TCutG.h"
#include "TF1.h"
#include "TParameter.h"
#include "TStatus.h"
#include "TLegend.h"
#include "TLine.h"
#include "TLatex.h"

#include "hloop.h"
#include "hcategorymanager.h"
#include "htool.h"
#include "htime.h"
#include "hphysicsconstants.h"
#include "hparticlestructs.h"
#include "hparticletracksorter.h"
#include "hparticlecand.h"

#include "heventheader.h"
#include "hparticleevtinfo.h"
#include "hgeantheader.h"
#include "hparticlecand.h"
#include "hparticlecandsim.h"
#include "hgeantkine.h"
#include "hstartdef.h"
#include "hstart2hit.h"
#include "hstart2raw.h"
#include "hstart2cal.h"
#include "hparticleevtchara.h"
#include "hgeantkine.h"
#include "hparticlemetamatcher.h"
#include "hdst.h"
#include "henergylosscorrpar.h"

#include "hmdclookupgeom.h"
#include "hmdccalparraw.h"
#include "hmdcdef.h"
#include "hmdctrackddef.h"

#include "hmdcseg.h"
#include "hmdcsegsim.h"
#include "hmdccellgroup.h"
#include "hmdccal1.h"
#include "hmdcraw.h"
#include "hmdcsizescells.h"
#include "hmdccal1sim.h"
#include "hmdcgetcontainers.h"

#endif // __INCLUDES_H__
