##############################################################################
#
#  Makefile for Hydra library libMyLib.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := FemtoCrap

SOURCE_FILES :=	FemtoAnalysis.cxx

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
